/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sports.team.management;

import model.CoachModel;
import dao.CoachDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author chitr
 */
public class Coach extends javax.swing.JFrame {

    /**
     * Creates new form Coach
     */
    public Coach() {
        initComponents();
        btnInsert.setEnabled(false);
        btnSearch.setEnabled(false);
        btnUpdate.setEnabled(false);
    }

    public void clear() {
        setVisible(false);
        new Coach().setVisible(true);
    }

    public void validateField() {
        String coachID = txtCoachID.getText();
        String coachName = txtCoachName.getText();

        String experience = txtExperience.getText();
        String sportsName = txtSportsName.getText();

        if (!coachID.equals("") && !coachName.equals("") && !experience.equals("") && !sportsName.equals("")) {
            btnInsert.setEnabled(true);
            btnUpdate.setEnabled(true);
        } else {
            btnInsert.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtCoachID = new javax.swing.JTextField();
        txtCoachName = new javax.swing.JTextField();
        txtExperience = new javax.swing.JTextField();
        txtSportsName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtGender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Coach ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 190, 87, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Coach Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 230, 87, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 270, 87, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Experience");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 310, 87, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Sports Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 350, -1, -1));

        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert icon (Custom).png"))); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 428, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update icon (Custom).png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 428, -1, -1));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search icon (Custom).png"))); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 428, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 509, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 509, -1, -1));

        txtCoachID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCoachIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtCoachID, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 190, 350, -1));

        txtCoachName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCoachNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtCoachName, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 230, 350, -1));

        txtExperience.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExperienceKeyReleased(evt);
            }
        });
        getContentPane().add(txtExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 310, 350, -1));

        txtSportsName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSportsNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtSportsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 350, 350, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Coach Table");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Experience", "Sports Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 580, 450));

        jLabel6.setText("* Click on the row to delete the entry");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 610, -1, -1));

        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 270, 350, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Coach bg.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        CoachModel coach = new CoachModel();
        coach.setCoachID(txtCoachID.getText());
        coach.setCoachName(txtCoachName.getText());
        coach.setGender((String)txtGender.getSelectedItem());
        coach.setExperience(Integer.parseInt(txtExperience.getText()));
        coach.setSportsName(txtSportsName.getText());
        CoachDao.insert(coach);
        clear();

    }//GEN-LAST:event_btnInsertActionPerformed

    private void txtCoachIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoachIDKeyReleased
        // TODO add your handling code here:
        validateField();
        if (!txtCoachID.getText().equals(""))
            btnSearch.setEnabled(true);
        else
            btnSearch.setEnabled(false);
    }//GEN-LAST:event_txtCoachIDKeyReleased

    private void txtCoachNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoachNameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtCoachNameKeyReleased

    private void txtExperienceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExperienceKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtExperienceKeyReleased

    private void txtSportsNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSportsNameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtSportsNameKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String coachID = model.getValueAt(index, 0).toString();
        String coachName = model.getValueAt(index, 1).toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete " + coachName, "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            CoachDao.delete(coachID);
            clear();
//            setVisible(false);
//            new Coach().setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<CoachModel> list = CoachDao.getAllRecords();
        Iterator<CoachModel> itr = list.iterator();
        while (itr.hasNext()) {
            CoachModel coachObj = itr.next();
            dtm.addRow(new Object[]{coachObj.getCoachID(), coachObj.getCoachName(), coachObj.getGender(), coachObj.getExperience(), coachObj.getSportsName()});
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String coachID = txtCoachID.getText();
        ArrayList <CoachModel> list = CoachDao.search(coachID);
        Iterator<CoachModel> itr = list.iterator();
        while (itr.hasNext()) {
            CoachModel coachObj = itr.next();
            txtCoachID.setText(coachObj.getCoachID());
            txtCoachName.setText(coachObj.getCoachName());
            txtGender.setSelectedItem(coachObj.getCoachName());
            txtExperience.setText(Integer.toString(coachObj.getExperience()));
            txtSportsName.setText(coachObj.getSportsName());
        }
        btnInsert.setEnabled(true);
        btnUpdate.setEnabled(true);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        CoachModel coach = new CoachModel();
        coach.setCoachID(txtCoachID.getText());
        coach.setCoachName(txtCoachName.getText());
        coach.setGender((String)txtGender.getSelectedItem());
        coach.setExperience(Integer.parseInt(txtExperience.getText()));
        coach.setSportsName(txtSportsName.getText());
        CoachDao.update(coach);
        clear();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCoachID;
    private javax.swing.JTextField txtCoachName;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JTextField txtSportsName;
    // End of variables declaration//GEN-END:variables
}
