/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sports.team.management;
import model.EquipmentsModel;
import model.PlayersModel;
import dao.EquipmentsDao;
import dao.PlayersDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author chitr
 */
public class Equipments extends javax.swing.JFrame {

    /**
     * Creates new form Equipments
     */
    public Equipments() {
        initComponents();
        btnInsert.setEnabled(false);
        btnSearch.setEnabled(false);
        btnUpdate.setEnabled(false);
    }
    
    public void clear(){
        setVisible(false);
        new Equipments().setVisible(true);
    }
    
    public void validateField(){
        String equipmentID = txtEquipmentID.getText();
        String equipmentName = txtEquipmentName.getText();
        String quantity = txtQuantity.getText();
        
        if(!equipmentID.equals("") && !equipmentName.equals("") && !quantity.equals("")){
            btnInsert.setEnabled(true);
            btnUpdate.setEnabled(true);
        } else {
            btnInsert.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEquipmentID = new javax.swing.JTextField();
        txtEquipmentName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtPlayerID = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Equipment ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 198, 118, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Equipment Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 238, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 278, 118, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Player ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 318, 118, -1));

        txtEquipmentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEquipmentIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtEquipmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 198, 283, -1));

        txtEquipmentName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEquipmentNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtEquipmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 238, 283, -1));

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 278, 283, -1));

        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert icon (Custom).png"))); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 393, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update icon (Custom).png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 393, -1, -1));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search icon (Custom).png"))); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 393, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 472, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 472, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Equipments Table");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 103, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "PlayerID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 146, 523, 490));

        jLabel6.setText("* Click on the row to delete the entry");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 650, 202, -1));

        getContentPane().add(txtPlayerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 318, 283, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Equipments bg.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEquipmentIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEquipmentIDKeyReleased
        // TODO add your handling code here:
        validateField();
        if (!txtEquipmentID.getText().equals(""))
            btnSearch.setEnabled(true);
        else
            btnSearch.setEnabled(false);
    }//GEN-LAST:event_txtEquipmentIDKeyReleased

    private void txtEquipmentNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEquipmentNameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtEquipmentNameKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        EquipmentsModel equipments = new EquipmentsModel();
        equipments.setEquipmentID(txtEquipmentID.getText());
        equipments.setEquipmentName(txtEquipmentName.getText());
        equipments.setQuantity(Integer.parseInt(txtQuantity.getText()));
        equipments.setPlayerID((String)txtPlayerID.getSelectedItem());
        EquipmentsDao.insert(equipments);
        clear();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<PlayersModel> list = PlayersDao.getAllRecords();
        Iterator<PlayersModel> itr = list.iterator();
        while (itr.hasNext()) {
            PlayersModel playersObj = itr.next();
            txtPlayerID.addItem(playersObj.getPlayerID());
        }
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<EquipmentsModel> list2 = EquipmentsDao.getAllRecords();
        Iterator<EquipmentsModel> itr2 = list2.iterator();
        while (itr2.hasNext()) {
            EquipmentsModel equipmentsObj = itr2.next();
            dtm.addRow(new Object[]{equipmentsObj.getEquipmentID(), equipmentsObj.getEquipmentName(), equipmentsObj.getQuantity(), equipmentsObj.getPlayerID()});
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String equipmentID = model.getValueAt(index, 0).toString();
        String equipmentName = model.getValueAt(index, 1).toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete " + equipmentName, "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            EquipmentsDao.delete(equipmentID);
            clear();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        EquipmentsModel equipments = new EquipmentsModel();
        equipments.setEquipmentID(txtEquipmentID.getText());
        equipments.setEquipmentName(txtEquipmentName.getText());
        equipments.setQuantity(Integer.parseInt(txtQuantity.getText()));
        equipments.setPlayerID((String)txtPlayerID.getSelectedItem());
        EquipmentsDao.update(equipments);
        clear();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String equipmentID = txtEquipmentID.getText();
        ArrayList <EquipmentsModel> list = EquipmentsDao.search(equipmentID);
        Iterator<EquipmentsModel> itr = list.iterator();
        while (itr.hasNext()) {
            EquipmentsModel equipmentsObj = itr.next();
            txtEquipmentID.setText(equipmentsObj.getEquipmentID());
            txtEquipmentName.setText(equipmentsObj.getEquipmentName());
            txtQuantity.setText(Integer.toString(equipmentsObj.getQuantity()));
            txtPlayerID.setSelectedItem(equipmentsObj.getPlayerID());
        }
        btnInsert.setEnabled(true);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEquipmentID;
    private javax.swing.JTextField txtEquipmentName;
    private javax.swing.JComboBox<String> txtPlayerID;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
