/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sports.team.management;

import javax.swing.JOptionPane;

/**
 *
 * @author chitr
 */
public class Home extends javax.swing.JFrame {
    
    public String email;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String userEmail) {
        initComponents();
        
        email = userEmail;
        if (!email.equals("admin@gmail.com"))
            btnVerifyUsers.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCoach = new javax.swing.JButton();
        btnTeam = new javax.swing.JButton();
        btnPlayers = new javax.swing.JButton();
        btnEquipments = new javax.swing.JButton();
        btnManager = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnVerifyUsers = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCoach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCoach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coach (Custom).png"))); // NOI18N
        btnCoach.setText("Coach");
        btnCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoachActionPerformed(evt);
            }
        });
        getContentPane().add(btnCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 160, -1));

        btnTeam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team (Custom).png"))); // NOI18N
        btnTeam.setText("Teams");
        btnTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeamActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 160, -1));

        btnPlayers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPlayers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/players (Custom).png"))); // NOI18N
        btnPlayers.setText("Players");
        btnPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayersActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 160, -1));

        btnEquipments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEquipments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/equipment (Custom).png"))); // NOI18N
        btnEquipments.setText("Equipments");
        btnEquipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnEquipments, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));

        btnManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manager (Custom).png"))); // NOI18N
        btnManager.setText("Manager");
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 160, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 670, 110, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 60, -1, -1));

        btnVerifyUsers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerifyUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        btnVerifyUsers.setText("Verify Users");
        btnVerifyUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyUsersActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerifyUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home 768p.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoachActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Coach().setVisible(true);
    }//GEN-LAST:event_btnCoachActionPerformed

    private void btnTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeamActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Teams().setVisible(true);
    }//GEN-LAST:event_btnTeamActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout", "Select", JOptionPane.YES_NO_OPTION);
        if (a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close the application", "Select", JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayersActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Players().setVisible(true);
    }//GEN-LAST:event_btnPlayersActionPerformed

    private void btnEquipmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipmentsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Equipments().setVisible(true);
    }//GEN-LAST:event_btnEquipmentsActionPerformed

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Manager().setVisible(true);
    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnVerifyUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyUsersActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new VerifyUsers().setVisible(true);
    }//GEN-LAST:event_btnVerifyUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoach;
    private javax.swing.JButton btnEquipments;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnPlayers;
    private javax.swing.JButton btnTeam;
    private javax.swing.JButton btnVerifyUsers;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
